devmodip/urls.py
from . import views
from .views import *
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("", main, name='main'),
    path("test", test, name='test'),
    path('login', user_login, name='login'),
    path('logout', user_logout, name='logout'),
    path('register', register, name='register'),
    path('graph', graph, name='graph'),
    path('math/', math, name='math'),
    path('create_plan/', create, name='create'),
    path('register',register,name='register'),
    path('graph',graph,name='graph'),
    path('lk', lk, name='lk'),
    path('about', about, name='about'),
    path('docs', docs, name='docs'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

netology/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('devmodip.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

devmodip/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.forms import ModelForm
from .models import *


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(label='Логин:',
        widget=forms.TextInput(attrs={'class': 'form-control', 'style': ''}))
    password = forms.CharField(label='Пароль:',
                               widget=forms.PasswordInput(
                                   attrs={'class': 'form-control', 'style': ''}))

class UserRegisterForm(ModelForm):
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

class CalcForm(forms.Form):
    prof_predmet = forms.ModelMultipleChoiceField(queryset=Ege.objects.all(), widget=forms.CheckboxSelectMultiple)
    hobbi = forms.CharField(label='Ваше хобби', widget=forms.TextInput(attrs={'class': 'form-control'}))
    want_prof = forms.ModelMultipleChoiceField(queryset=Profession.objects.all(), widget=forms.CheckboxSelectMultiple)
    want_spec = forms.ModelMultipleChoiceField(queryset=Spec.objects.all(), widget=forms.CheckboxSelectMultiple)

templates/about.html
{% extends 'main.html' %}
{% load static %}
{% block title %}О нас{% endblock %}


{% block content %}
    <header class="page-header page-header-dark bg-gradient-primary-to-secondary">
                        <div class="page-header-content pt-10">
                            <div class="container text-center">
                                <div class="row justify-content-center">
                                    <div class="col-lg-8">
                                        <img src="{% static 'assets/pict/about_st_logo.png' %}" style="width: 80%">
{#                                        <h1 class="page-header-title mb-2">О StarTrek Team</h1>#}
                                        <p class="page-header-text">ее участниках и контакты</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="svg-border-rounded text-white">
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 144.54 17.34" preserveAspectRatio="none" fill="currentColor"><path d="M144.54,17.34H0V0H144.54ZM0,0S32.36,17.34,72.27,17.34,144.54,0,144.54,0"></path></svg>
                        </div>
                    </header>
    <section class="bg-white py-10">
                        <div class="container">
                            <div class="row justify-content-center">
                                <div class="col-lg-10">
{#                                    <h2 class="mb-4">A quick guide to our company culture</h2>#}
{#                                    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolor, eos quisquam expedita quo officiis porro provident laborum. Earum, consequatur provident, ipsam at excepturi rerum laborum aliquam facere molestias mollitia recusandae.</p>#}
{#                                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias, ipsam? Perspiciatis sunt voluptatum officia non harum, dolores omnis fugiat nam ad optio cumque molestiae impedit dignissimos velit commodi aliquid iure?</p>#}
{#                                    <p class="mb-0">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Exercitationem sapiente natus architecto aut porro! Vitae iusto praesentium recusandae debitis, cumque illum amet suscipit rem pariatur, magni iure laborum inventore in!</p>#}
{#                                    <hr class="my-5">#}
{#                                    <h4 class="mb-4">#}
{#                                        <div class="icon-stack bg-primary text-white mr-2"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-right"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg></div>#}
{#                                        This is what we do#}
{#                                    </h4>#}
{#                                    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolor, eos quisquam expedita quo officiis porro provident laborum. Earum, consequatur provident, ipsam at excepturi rerum laborum aliquam facere molestias mollitia recusandae.</p>#}
{#                                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias, ipsam? Perspiciatis sunt voluptatum officia non harum, dolores omnis fugiat nam ad optio cumque molestiae impedit dignissimos velit commodi aliquid iure?</p>#}
{#                                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Exercitationem sapiente natus architecto aut porro! Vitae iusto praesentium recusandae debitis, cumque illum amet suscipit rem pariatur, magni iure laborum inventore in!</p>#}
{#                                    <div class="card bg-light shadow-none">#}
{#                                        <div class="card-body">#}
{#                                            <h6>Questions you should ask yourself</h6>#}
{#                                            <ul class="mb-0">#}
{#                                                <li class="text-italic">Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed soluta fugiat eveniet, dignissimos facere quisquam, odit suscipit aliquid magnam,?</li>#}
{#                                            </ul>#}
{#                                        </div>#}
{#                                    </div>#}
{#                                    <hr class="my-5">#}
                                    <img src="{% static 'assets/pict/paltusov.png' %}" style="width: 20%; border-radius: 50%">
                                    <h4 class="mb-4">
                                        <div class="icon-stack bg-primary text-white mr-2"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-right"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg></div>
                                        Никита Палтусов. Директор
                                    </h4>
                                    <p class="lead">«Когда вы создаете собственную компанию, это больше похоже на искусство, чем на науку, ведь вы ничего не знаете. Вместо решения профильных проблем, попробуйте решить что-нибудь глубоко личное для вас самих. Всё будет идеально, если вы будете обычным человеком и просто решите собственную проблему способом, который может помочь миллионам других людей».</p>

                                    <hr class="my-5">
                                    <img src="{% static 'assets/pict/polyakov.png' %}" style="width: 20%; border-radius: 50%">
                                    <h4 class="mb-4">
                                        <div class="icon-stack bg-primary text-white mr-2"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-right"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg></div>
                                        Александр Поляков. Фронт-энд специалист
                                    </h4>
                                    <p class="lead">«По-хорошему, больше половины популярных работ были написаны просто отвратительно. Вернее, хайп вокруг них совершенно не соответствует качеству кода и уровню поддержки от организаторов. Но поскольку на Front подсаживалась сразу куча людей, он выживал и продолжал существовать».</p>

                                    <hr class="my-5">
                                    <img src="{% static 'assets/pict/simakov.png' %}" style="width: 20%; border-radius: 50%">
                                    <h4 class="mb-4">
                                        <div class="icon-stack bg-primary text-white mr-2"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-right"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg></div>
                                        Антон Симаков. Бэк-энд специалист
                                    </h4>
                                    <p class="lead">«Пользователь совершает действие, а реакция сервиса или сайта на него затрагивает нужную часть бэкенда. В это понятие входит всё, что позволяет вам реализовывать логику работы тех функций, которые предоставляет интерфейс».</p>

                                    <hr class="my-5">
                                    <img src="{% static 'assets/pict/shalkin.png' %}" style="width: 20%; border-radius: 50%">
                                    <h4 class="mb-4">
                                        <div class="icon-stack bg-primary text-white mr-2"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-right"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg></div>
                                        Дмитрий Шалькин. Специалист БД
                                    </h4>
                                    <p class="lead">«Когда вы создаете собственную компанию, это больше похоже на искусство, чем на науку, ведь вы ничего не знаете. Вместо решения профильных проблем, попробуйте решить что-нибудь глубоко личное для вас самих. Всё будет идеально, если вы будете обычным человеком и просто решите собственную проблему способом, который может помочь миллионам других людей».</p>

                                    <hr class="my-5">
                                        <img src="{% static 'assets/pict/dudkin' %}" style="width: 20%; border-radius: 50%">
                                    <h4 class="mb-4">
                                        <div class="icon-stack bg-primary text-white mr-2"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-right"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg></div>
                                        Андрей Дудкин. Руководитель
                                    </h4>
                                    <p class="lead">«Я никогда не готовился стать руководителем. Я всегда готовился стать хорошим членом команды, хорошим коллегой».</p>

                                        {#                                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque laboriosam consequuntur iusto vero consequatur beatae, tempore voluptatem rerum sit facilis aut ea optio eaque quaerat, libero recusandae soluta molestiae veniam.</p>#}
{#                                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae, ut! Ut ipsum debitis numquam. Perferendis, laudantium! Itaque ab velit eaque magnam quis quam libero saepe nobis culpa. Vitae, dignissimos iusto.</p>#}
{#                                    <div class="card bg-light shadow-none">#}
{#                                        <div class="card-body">#}
{#                                            <h6>Questions you should ask yourself</h6>#}
{#                                            <ul class="mb-0">#}
{#                                                <li class="text-italic">Lorem ipsum dolor sit amet, consectetur adipisicing elit?</li>#}
{#                                                <li class="text-italic">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas nobis illum nam?</li>#}
{#                                            </ul>#}
{#                                        </div>#}
{#                                    </div>#}
{#                                    <hr class="my-5">#}
{#                                    <h4>Feedback</h4>#}
{#                                    <p class="lead">In the spirit of thinking rigorously, we’d love your open and honest feedback on this guide. <a href="#!">Let us know what you think</a>.</p>#}
{#                                    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Harum culpa optio nihil id distinctio excepturi dignissimos, iure totam minima, natus ducimus.</p>#}
                                </div>
                            </div>
                        </div>
                        <div class="svg-border-rounded text-dark">
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 144.54 17.34" preserveAspectRatio="none" fill="currentColor"><path d="M144.54,17.34H0V0H144.54ZM0,0S32.36,17.34,72.27,17.34,144.54,0,144.54,0"></path></svg>
                        </div>
                    </section>
{% endblock %}

{% block script %}

{% endblock %}

templates/graph.html
{% extends 'main.html' %}
{% load static %}
{% block title %}Подбор учебного плана{% endblock %}


{% block content %}
    <style type="text/css">
    li {
        list-style-type: none;
    }
    </style>
    <header class="page-header page-header-dark bg-gradient-primary-to-secondary">
        <div class="page-header-content pt-10" style="padding-top: 1rem !important;">
        <a id="create" style="display: none" class="text-light btn-teal btn rounded-pill px-4 ml-lg-4 mt-3">Сохранить учебный план</a>
        <div id="cy" style="border-radius: 0.5rem; width: 100%; height: 900px; position: absolute"></div>

{#            <div class="container">#}
{#                <div class="row align-items-center">#}
                <div align="right">
                    <div align="left" class="col-md-4 mb-4">
                        <div class="card rounded-lg text-dark">
                            <div class="card-header py-4">Параметры</div>
                            <div class="card-body">
                                <form action="">
                                    {% csrf_token %}
                                    <label>Профилирующий предмет</label>
                                    <div class="overflow-auto" style="height: 200px">
                                        <ul id="id_prof_predmet">
                                            {% for item in ege %}
                                                <li>
                                                    <label for="id_prof_predmet_{{ item.id }}">
                                                        <input type="checkbox" class="pred" name="prof_predmet_{{ item.id }}" value="{{ item.id }}"
                                                               id="id_prof_predmet_{{ item.id }}"> {{ item.name }}
                                                    </label>
                                                </li>
                                            {% endfor %}
                                        </ul>
                                    </div>

                                    <label for="id_hobbi">Ваше хобби</label>

                                    <input type="text" name="hobbi" class="form-control" required="" id="id_hobbi">

                                    <label>Желаемая профессия</label>
                                    <div class="overflow-auto" style="height: 200px">
                                        <ul id="id_want_prof">
                                            {% for item in prof %}
                                                <li>
                                                    <label for="id_want_prof_{{ item.id }}"><input class="prof" type="checkbox"
                                                                                                   name="want_prof_{{ item.id }}"
                                                                                                   value="{{ item.id }}"
                                                                                                   id="id_want_prof_{{ item.id }}"> {{ item.name }}
                                                    </label>
                                                </li>
                                            {% endfor %}
                                        </ul>
                                    </div>

                                    <label>Желаемая специальность</label>
                                    <div class="overflow-auto" style="height: 200px">
                                        <ul id="id_want_spec">
                                            {% for item in spec %}
                                                <li>
                                                    <label for="id_want_spec_{{ item.id }}"><input class="spec" type="checkbox"
                                                                                                   name="want_spec_{{ item.id }}"
                                                                                                   value="{{ item.id }}"
                                                                                                   id="id_want_spec_{{ item.id }}"> {{ item.name }}
                                                    </label>
                                                </li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                <a id="submit" class="text-light btn-teal btn rounded-pill px-4 ml-lg-4 mt-3">Построить учебный план</a>
                                <a id="sort" class="text-light btn-teal btn rounded-pill px-4 ml-lg-4 mt-3">Сортировать</a>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                    {#                    <div class="col-lg-6 d-none d-lg-block" data-aos="fade-up" data-aos-delay="50"><img#}
                    {#                            class="img-fluid" src="{% static 'assets/pict/reg_pict.png' %}"/></div>#}
{#                </div>#}
{#            </div>#}
        </div>
        <div class="svg-border-rounded text-white">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 144.54 17.34" preserveAspectRatio="none"
                 fill="currentColor">
                <path d="M144.54,17.34H0V0H144.54ZM0,0S32.36,17.34,72.27,17.34,144.54,0,144.54,0"></path>
            </svg>
        </div>
    </header>

{% endblock %}

{% block script %}

    <script>
        jQuery(function () {
            var cy = cytoscape({
                container: $('#cy'),

                elements: {{ data|safe }},

                style: [{
                    selector: 'node',
                    style: {
                        'background-color': 'data(bg)',
                        'shape': 'star'
                    }
                },
                    {
                        selector: 'edge',
                        style: {
                            'width': 5,
                            'line-color': 'data(bg)',
                            'target-arrow-color': 'data(bg)',
                            'target-arrow-shape': 'triangle',
                            'curve-style': 'bezier'
                        }
                    },
                    {
                        selector: 'label',
                        style: {
                            'color': 'white'
                        }
                    }
                ],
                layout: {
                    name: 'random',
                    fit:false
                },
            });

            cy.on('click', 'node', function (evt) {
                var node = evt.target;
                if (node.style().label !== '') {
                    node.style({
                        label: ''
                    })
                } else {
                    node.style({
                        label: node.id()
                    })
                }
            })


            $('#sort').click(function () {
                cy.layout({
                    name:'circle',
                }).run(5000);
            })


            $('#submit').click(function () {
                let data = {'csrfmiddlewaretoken': $('input[type="hidden"]').val()};
                $('input.spec').each(function () {
                   if($(this).is(':checked')){
                       data[$(this).attr('name')] = $(this).attr('name');
                   }
                });
                $('input.prof').each(function () {
                   if($(this).is(':checked')){
                       data[$(this).attr('name')] = $(this).attr('name');
                   }
                });
                $('input.pred').each(function () {
                   if($(this).is(':checked')){
                       data[$(this).attr('name')] = $(this).attr('name');
                   }
                });
                data['hobbi'] = $('#id_hobbi').val();
                $.ajax({
                    url: 'math/',
                    type: 'POST',
                    data: data,
                    success: function (data) {
                        console.log(data);
                            {#cy.removeData();#}
                        cy.destroy();
                        cy = cytoscape({
                            container: $('#cy'),

                            elements: data['data'],

                            style: [{
                                selector: 'node',
                                style: {
                                    'background-color': 'data(bg)',
                                    'shape': 'star'
                                }
                            },
                                {
                                    selector: 'edge',
                                    style: {
                                        'width': 5,
                                        'line-color': 'data(bg)',
                                        'target-arrow-color': 'data(bg)',
                                        'target-arrow-shape': 'triangle',
                                        'curve-style': 'bezier'
                                    }
                                },
                                {
                                    selector: 'label',
                                    style: {
                                        'color': 'white'
                                    }
                                }
                            ],
                            layout: {
                                name: 'circle',
                                fit: false
                            },
                        });

                        cy.on('click', 'node', function (evt) {
                            var node = evt.target;
                            if (node.style().label !== '') {
                                node.style({
                                    label: ''
                                })
                            } else {
                                node.style({
                                    label: node.id()
                                })
                            }
                        })
                        $('#create').show()
                        $('#create').click(function () {
                            let num = {'csrfmiddlewaretoken': $('input[type="hidden"]').val()};
                            for (var item in data['data']){
                                if (!data['data'][item]['data']['source']) {
                                    num[data['data'][item]['data']['id']] = data['data'][item]['data']['id'];
                                }
                            }
                            $.ajax({
                                url:'create_plan/',
                                type:'POST',
                                data:num,
                                success: function (data) {
                                        if (data['ok']) {
                                            return location.href = location.origin + '/lk';
                                        }else{
                                            return location.href = location.origin + '/login';
                                        }
                                }
                            })
                        })
                        }
                })
            });
        });
    </script>

{% endblock %}

templates/login.html
{% extends 'main.html' %}
{% load static %}
{% block title %}Авторизация{% endblock %}

{% block content %}
    <header class="page-header page-header-dark bg-gradient-primary-to-secondary">
        <div class="page-header-content pt-10">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-6 d-none d-lg-block" data-aos="fade-up" data-aos-delay="50"><img
                            class="img-fluid" src="{% static 'assets/pict/login_pict.png' %}"/></div>
                    <div align="left" class="col-md-4 mb-4">
                        <div class="card rounded-lg text-dark">
                            <div class="card-header py-4">Авторизация</div>
                            <div class="card-body">
                                <form method="post">
                                    {% csrf_token %}
                                    <div class="form-row">
                                        <div class="form-group col-md">
                                            <label class="small text-gray-600" for="leadCapFirstName">Логин:</label>
                                            <input name="username" class="form-control rounded-pill"
                                                   id="leadCapFirstName" type="text">
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="form-group col-md">
                                            <label class="small text-gray-600" for="leadCapEmail">Пароль:</label>
                                            <input name="password" class="form-control rounded-pill" id="leadCapEmail"
                                                   type="password">
                                        </div>
                                    </div>
                                    <div align="center">
                                        <button class="btn btn-primary btn-marketing btn-block rounded-pill mt-2 col-md-5"
                                                type="submit">Войти
                                        </button>
                                        <a href="{% url 'register' %}">Регистрация</a>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="svg-border-rounded text-white">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 144.54 17.34" preserveAspectRatio="none"
                 fill="currentColor">
                <path d="M144.54,17.34H0V0H144.54ZM0,0S32.36,17.34,72.27,17.34,144.54,0,144.54,0"></path>
            </svg>
        </div>
    </header>
{% endblock %}

templates/test.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset=utf-8 />
    <meta name="viewport" content="width=device-width, user-scalable=no" />

    <title>Wine &amp; Cheese Map</title>
    <meta name="Description" CONTENT="An interactive visualisation to explore wine and cheese pairings">

    <link href="{% static 'test_dist/bundle.css' %}" rel="stylesheet">
    <link rel="shortcut icon" type="image/png" href="icon.png">
  </head>
  <body>
    <div id="loader" class="loader">
      <div class="loader-icon"></div>
      <h1>Wine &amp; Cheese Map</h1>
    </div>

    <script src="{% static 'test_dist/polyfills.js' %}"></script>
    <script src="{% static 'test_dist/bundle.js' %}"></script>

    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            },
                i[r].l = 1 * new Date();
            a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');
        ga('create', 'UA-155159-12', 'auto');
        ga('send', 'pageview');
    </script>

  </body>
</html>